pipeline:
  identifier: Build_habyyb_demo_app_next_1710752235386
  name: Build demo-app-next
  orgIdentifier: default
  projectIdentifier: DIP
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github_OAuth_1710752134937
        repoName: habyyb/demo-app-next
  stages:
    - stage:
        identifier: build1
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: installdependencies
                  name: install dependencies
                  spec:
                    command: npm install
                  timeout: ""
                  type: Run
              - step:
                  identifier: lint
                  name: lint
                  spec:
                    command: npm run lint
                  timeout: ""
                  type: Run
              - step:
                  identifier: build
                  name: build
                  spec:
                    command: npm run build
                  timeout: ""
                  type: Run
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
